version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_segura_123
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Gerenciador Visual (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_painel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: aluno@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
